server:
  port: 8091
#simple:
#  common: /tmp
helium:
  id: heliumboot
  xmlEnable: false
  environmentsNode:
    variables:
      - key: PRIVATE_IP
        value: 127.0.0.1
      - key: RPC_PORT
        value: 7001
  beans:
    task: org.helium.sample.boot
    service: org.helium.sample.boot



