server:
  port: 8092
spring:
  application:
    name: cloud-rpc-provider

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 8192
  registry:
    address: zookeeper://10.10.220.122:7998
  scan:
    base-packages: org.helium.sample.boot.service
helium:
  task:
    package: org.helium.sample.boot.task
