server:
  port: 8091
spring:
  application:
    name: cloud-rpc-provider

dubbo:
  protocol:
    name: dubbo
    port: 8191
  registry:
    address: zookeeper://10.10.220.121:7998
  scan:
    base-packages: org.helium.sample.boot.service
helium:
  task:
    package: org.helium.sample.boot.task



